[package]
name = "server"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4", features = ["derive"] }
futures = { version = "0.3" }
hmac = { version = "0.12" }
jwt = { version = "0.16" }
poem = { version = "1.3", features = ["cookie", "static-files"] }
poem-openapi = { version = "3.0", features = ["swagger-ui"] }
sha2 = { version = "0.10" }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.3", features = ["fs", "trace"] }
tower = { version = "0.4" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1" }
yew = { version = "0.21", features = ["ssr"] }

ui = { path = "../ui" }
