[package]
name = "ui"
edition.workspace = true
version.workspace = true

[dependencies]
async-trait = { version = "0.1.74" }
log = { version = "0.4" }
yew = { version = "0.21", default-features = false }
yew-router = { version = "0.18", default-features = false }
